@AquaOsCalendar_HostAddress = http://localhost:5233

GET {{AquaOsCalendar_HostAddress}}/api/calendar/
Accept: application/json

###

GET {{AquaOsCalendar_HostAddress}}/api/calendar/1/calendar.ics

###

POST {{AquaOsCalendar_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
